"""Контракты пассивных видов.

Вид не содержит логики: он сообщает о действиях пользователя через события
(Event) и показывает то, что ему передал презентер. Презентеры работают
только с этими интерфейсами, поэтому их можно тестировать без Qt.
"""
from typing import Optional, Protocol, Sequence

from masslab.events import Event
from masslab.views.viewmodels import PlotData, ReportData, SchemeData


class IWorkspaceView(Protocol):
    """Панель прибора: U и L, спектр, траектории, схема, считывание курсора."""
    voltage_changed: Event       # (int) В
    length_changed: Event        # (float) м
    log_scale_toggled: Event     # (bool)
    spectrum_hovered: Event      # (float | None) время под курсором, мкс

    def set_voltage_range(self, minimum: int, maximum: int, step: int) -> None: ...
    def set_voltage(self, value: int) -> None: ...
    def set_length_range(self, minimum: float, maximum: float, step: float) -> None: ...
    def set_length(self, value: float) -> None: ...
    def set_length_visible(self, visible: bool) -> None: ...
    def set_log_scale(self, enabled: bool) -> None: ...
    def set_parameters(self, text: str) -> None: ...
    def show_spectrum(self, plot: PlotData) -> None: ...
    def show_trajectories(self, plot: PlotData, animate: bool) -> None: ...
    def show_scheme(self, scheme: SchemeData) -> None: ...
    def clear_plots(self, message: str) -> None: ...
    def show_cursor(self, x: float, y: Optional[float], text: str) -> None: ...
    def hide_cursor(self) -> None: ...
    def set_readout(self, text: str) -> None: ...


class IIonLauncherView(Protocol):
    """Выбор и запуск ионов (задание 1 и песочница)."""
    workspace: IWorkspaceView
    launch_requested: Event
    double_charge_toggled: Event     # (bool)

    def set_element_choices(self, items: Sequence[tuple]) -> None: ...
    def set_selected_elements(self, symbols: Sequence[str]) -> None: ...
    def selected_elements(self) -> list: ...
    def double_charge_enabled(self) -> bool: ...
    def set_double_charge(self, enabled: bool) -> None: ...
    def show_launch_feedback(self, text: str, ok: Optional[bool]) -> None: ...
    def show_flight_table(self, rows: Sequence[Sequence[str]]) -> None: ...
    def show_feedback(self, text: str, ok: Optional[bool]) -> None: ...
    def show_reference(self, rows: Sequence[Sequence[str]]) -> None: ...


class ILoginView(Protocol):
    start_requested: Event
    secret_entered: Event            # (str) скрытое поле
    teacher_demo_requested: Event    # режим преподавателя: работа с ответами
    sandbox_requested: Event         # режим преподавателя: свободный прибор

    def student_name(self) -> str: ...
    def student_group(self) -> str: ...
    def show_error(self, text: str) -> None: ...
    def clear_secret(self) -> None: ...
    def show_teacher_panel(self, visible: bool) -> None: ...
    def reset(self) -> None: ...


class IQuizView(Protocol):
    answer_selected: Event           # (int) номер варианта
    next_requested: Event
    prev_requested: Event
    finish_requested: Event
    result_action_requested: Event

    def show_question(self, number: int, total: int, text: str, options: Sequence[str],
                      selected: Optional[int], correct: Optional[int] = None) -> None: ...
    def set_navigation(self, can_prev: bool, can_next: bool, can_finish: bool) -> None: ...
    def set_progress(self, answered: int, total: int) -> None: ...
    def show_result(self, title: str, text: str, details: Sequence[str],
                    passed: bool, action_text: str) -> None: ...


class IDemoView(IIonLauncherView, Protocol):
    """Задание 1."""
    answer_selected: Event           # (int вопрос, int вариант)
    check_requested: Event

    def show_questions(self, questions: Sequence) -> None: ...   # [QuestionItem]
    def show_hint(self, text: Optional[str]) -> None: ...


class ISandboxView(IIonLauncherView, Protocol):
    """Песочница преподавателя: прибор без заданий."""
    gas_toggled: Event               # (bool)
    exit_requested: Event

    def set_gas(self, enabled: bool) -> None: ...


class IElementView(Protocol):
    """Задание 2."""
    workspace: IWorkspaceView
    check_requested: Event

    def set_options(self, labels: Sequence[str], correct: Optional[int] = None) -> None: ...
    def selected_option(self) -> Optional[int]: ...
    def show_answer(self, text: Optional[str]) -> None: ...
    def time_text(self) -> str: ...
    def mass_text(self) -> str: ...
    def clear_inputs(self) -> None: ...
    def show_feedback(self, text: str, ok: Optional[bool]) -> None: ...
    def show_hint(self, text: Optional[str]) -> None: ...
    def show_reference(self, rows: Sequence[Sequence[str]]) -> None: ...


class IAlloyView(Protocol):
    """Задание 3: шаг 1 — элементы образца, шаг 2 — сплав."""
    workspace: IWorkspaceView
    elements_check_requested: Event  # шаг 1
    check_requested: Event           # шаг 2

    def set_element_choices(self, items: Sequence[tuple],
                            correct: Optional[Sequence[str]] = None) -> None: ...
    def selected_elements(self) -> list: ...
    def show_elements_feedback(self, text: str, ok: Optional[bool]) -> None: ...
    def set_step(self, step: int) -> None: ...
    def set_options(self, labels: Sequence[str], correct: Optional[int] = None) -> None: ...
    def selected_option(self) -> Optional[int]: ...
    def show_answer(self, text: Optional[str]) -> None: ...
    def show_feedback(self, text: str, ok: Optional[bool]) -> None: ...
    def show_hint(self, text: Optional[str]) -> None: ...
    def show_reference(self, rows: Sequence[Sequence[str]]) -> None: ...


class IReportView(Protocol):
    new_session_requested: Event
    exit_requested: Event
    export_requested: Event

    def show_report(self, report: ReportData) -> None: ...
    def show_feedback_qr(self, url: str, text: str) -> None: ...
    def ask_save_path(self, default_name: str) -> Optional[str]: ...
    def show_export_result(self, text: str, ok: bool) -> None: ...


class ITheoryView(Protocol):
    """Методичка: разделы с иллюстрациями."""
    section_selected: Event          # (int)
    next_requested: Event
    prev_requested: Event
    resolution_voltage_changed: Event   # (int) В — ползунок интерактивного спектра

    def open(self) -> None: ...
    def set_sections(self, titles: Sequence[str]) -> None: ...
    def set_resolution_range(self, minimum: int, maximum: int, step: int, value: int) -> None: ...
    def show_section(self, index: int, total: int, title: str, points_html: str, formula: str,
                     caption: str, visual) -> None: ...      # visual: TheoryVisual
    def set_navigation(self, can_prev: bool, can_next: bool) -> None: ...
    def show_resolution(self, plot: PlotData, text: str) -> None: ...


class IMainView(Protocol):
    login: ILoginView
    quiz: IQuizView
    demo: IDemoView
    element: IElementView
    alloy: IAlloyView
    report: IReportView
    sandbox: ISandboxView
    theory: ITheoryView
    tick: Event                      # раз в секунду
    theory_requested: Event
    help_requested: Event
    tour_next: Event
    tour_skip: Event

    def show_page(self, page: str) -> None: ...
    def set_stages(self, stages: Sequence[tuple]) -> None: ...
    def set_timer(self, text: str) -> None: ...
    def show_message(self, title: str, text: str) -> None: ...
    def confirm(self, title: str, text: str) -> bool: ...
    def set_close_confirmation(self, text: Optional[str]) -> None: ...
    def close_app(self) -> None: ...
    def show_tour_step(self, target: str, title: str, text: str,
                       index: int, total: int) -> None: ...
    def hide_tour(self) -> None: ...
