"""Контракты пассивных видов.

Вид не содержит логики: он сообщает о действиях пользователя через события
(Event) и показывает то, что ему передал презентер. Презентеры работают
только с этими интерфейсами, поэтому их можно тестировать без Qt.
"""
from typing import Optional, Protocol, Sequence

from masslab.events import Event
from masslab.views.viewmodels import PlotData, ReportData


class IWorkspaceView(Protocol):
    """Панель прибора: напряжение, спектр, траектории, считывание курсора."""
    voltage_changed: Event       # (int) В
    log_scale_toggled: Event     # (bool)
    spectrum_hovered: Event      # (float | None) время под курсором, мкс

    def set_voltage_range(self, minimum: int, maximum: int, step: int) -> None: ...
    def set_voltage(self, value: int) -> None: ...
    def set_log_scale(self, enabled: bool) -> None: ...
    def set_parameters(self, text: str) -> None: ...
    def show_spectrum(self, plot: PlotData) -> None: ...
    def show_trajectories(self, plot: PlotData, animate: bool) -> None: ...
    def clear_plots(self, message: str) -> None: ...
    def show_cursor(self, x: float, y: Optional[float], text: str) -> None: ...
    def hide_cursor(self) -> None: ...
    def set_readout(self, text: str) -> None: ...


class ILoginView(Protocol):
    start_requested: Event

    def student_name(self) -> str: ...
    def student_group(self) -> str: ...
    def show_error(self, text: str) -> None: ...
    def reset(self) -> None: ...


class IQuizView(Protocol):
    answer_selected: Event           # (int) номер варианта
    next_requested: Event
    prev_requested: Event
    finish_requested: Event
    result_action_requested: Event

    def show_question(self, number: int, total: int, text: str,
                      options: Sequence[str], selected: Optional[int]) -> None: ...
    def set_navigation(self, can_prev: bool, can_next: bool, can_finish: bool) -> None: ...
    def set_progress(self, answered: int, total: int) -> None: ...
    def show_result(self, title: str, text: str, details: Sequence[str],
                    passed: bool, action_text: str) -> None: ...


class IDemoView(Protocol):
    """Задание 1."""
    workspace: IWorkspaceView
    launch_requested: Event
    answer_selected: Event           # (int вопрос, int вариант)
    check_requested: Event

    def set_element_choices(self, items: Sequence[tuple]) -> None: ...
    def set_selected_elements(self, symbols: Sequence[str]) -> None: ...
    def selected_elements(self) -> list: ...
    def show_flight_table(self, rows: Sequence[Sequence[str]]) -> None: ...
    def show_questions(self, questions: Sequence[tuple]) -> None: ...
    def show_feedback(self, text: str, ok: Optional[bool]) -> None: ...
    def show_reference(self, rows: Sequence[Sequence[str]]) -> None: ...


class IElementView(Protocol):
    """Задание 2."""
    workspace: IWorkspaceView
    check_requested: Event

    def set_options(self, labels: Sequence[str]) -> None: ...
    def selected_option(self) -> Optional[int]: ...
    def mass_text(self) -> str: ...
    def clear_inputs(self) -> None: ...
    def show_feedback(self, text: str, ok: Optional[bool]) -> None: ...
    def show_reference(self, rows: Sequence[Sequence[str]]) -> None: ...


class IAlloyView(Protocol):
    """Задание 3."""
    workspace: IWorkspaceView
    check_requested: Event

    def set_options(self, labels: Sequence[str]) -> None: ...
    def selected_option(self) -> Optional[int]: ...
    def clear_inputs(self) -> None: ...
    def show_feedback(self, text: str, ok: Optional[bool]) -> None: ...
    def show_reference(self, rows: Sequence[Sequence[str]]) -> None: ...


class IReportView(Protocol):
    new_session_requested: Event
    exit_requested: Event

    def show_report(self, report: ReportData) -> None: ...


class IMainView(Protocol):
    login: ILoginView
    quiz: IQuizView
    demo: IDemoView
    element: IElementView
    alloy: IAlloyView
    report: IReportView
    tick: Event                      # раз в секунду

    def show_page(self, page: str) -> None: ...
    def set_stages(self, stages: Sequence[tuple]) -> None: ...
    def set_student(self, text: str) -> None: ...
    def set_timer(self, text: str) -> None: ...
    def show_message(self, title: str, text: str) -> None: ...
    def confirm(self, title: str, text: str) -> bool: ...
    def set_close_confirmation(self, text: Optional[str]) -> None: ...
    def close_app(self) -> None: ...
